### ISSUE TITLE
returns -1

### ISSUE THREAD

**Issue by Aelphy** [ToruNiina/lbvh#1]
Hi, I just got `-1` as `nest.first` here `const auto nest = lbvh::query_device(bvh_dev, lbvh::nearest(point), distance_calculator())`; 
Could you help to explain what is the reason ?

**Comment by Aelphy** [comment]
I actually need the index of the closest object.

**Comment by ToruNiina** [comment]
Hi, thank you for reporting the problem.

It's a bug. And I think I found the reason so I will commit it soon. I hope this change fixes your problem.

Actually, this library is not so strictly tested (I just tested it with a small number of sizeless particles), any kind of bugs may remain.

But these days I'm a little busy, so my response would be slow. Sorry!
